{"name": "test_c", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 2", "trace": "self = <test_case.TestCase object at 0x1042533b0>\n\n    def test_c(self):\n>       assert 1 > 2\nE       assert 1 > 2\n\ntestcase/test_case.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "48051df5-557f-4bc8-a0a6-73ef16414cb6-attachment.txt", "type": "text/plain"}], "start": 1722151216238, "stop": 1722151216238, "uuid": "36744174-b2b0-4c3c-a981-8f7ddb844d1f", "historyId": "68d1e65c9495387227d25966efa37999", "testCaseId": "68d1e65c9495387227d25966efa37999", "fullName": "testcase.test_case.TestCase#test_c", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "XiaofeideMacBook-Pro.local"}, {"name": "thread", "value": "26072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_case"}]}