{"name": "test_c", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 2", "trace": "self = <test_case.TestCase object at 0x104169760>\n\n    def test_c(self):\n>       assert 1 > 2\nE       assert 1 > 2\n\ntestcase/test_case.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "8d1c3bca-709e-46b9-a8a0-739da201e87a-attachment.txt", "type": "text/plain"}], "start": 1722151245307, "stop": 1722151245307, "uuid": "55f594f2-fe8d-4a80-8b18-ca815aa2f3bd", "historyId": "68d1e65c9495387227d25966efa37999", "testCaseId": "68d1e65c9495387227d25966efa37999", "fullName": "testcase.test_case.TestCase#test_c", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "XiaofeideMacBook-Pro.local"}, {"name": "thread", "value": "26114-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_case"}]}